<?php 


foreach ($contacts as $contact)
{	
	echo '<br />';
	echo $contact->id;
	echo '<br />';
	echo $contact->userLastName;
	echo '<br /> --------------- <br />';
	
}

echo $HelloWorld;

$form = $this->contactForm;
echo $this->form()->openTag($form);
echo $this->formRow($form->get('userName'));
echo $this->formRow($form->get('userLastName'));
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag($form);

?>